name: textPlusData blog
markdown: kramdown
theme: jekyll-theme-slate
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      author_profile: true
footer:
  links:
    - label: "Twitter"
      url: "https://twitter.com/fakecheck"
plugins:
  - jekyll-sitemap
